# Site settings
title: Startup Chiang Mai | A Repo for all things startup related in Chiang Mai, Thailand.
description: "A minimal blog template, build with Jekyll."
url: "http://www.startupchiangmai.com/"
author:
  name: "Lily Bruns"
  email: "lily@cnxweb.site"
  url: "http://cnxweb.site/about"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins_dir:
  - jekyll-paginate

# # Custom variables
# version: "1.1.0"

# Options
reverse: true
