# Site
name: "Startup Chiang Mai"
title: "Startup Chiang Mai"
description: "A repository for all things start up and digital in Chiang Mai"
meta_description: "A repository for all things start up and digital in Chiang Mai"
logo: 'assets/images/logo.png'
logo-small: 'assets/images/logo-small.png'
favicon: 'assets/images/logo.png'
baseurl: /startupchiangmai
google_analytics: ''
# disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Lily:
    name: Lily
    display_name: Lily
    gravatar: '2fe6fb927f04d5b181c96f15b0a8e5b6'
    email: lily@cnxweb.site
    web: lilybruns.com
    twitter: https://twitter.com/itslilybruns
    description: "Coder, copywriter, consultant, and cat lady. I also enjoy travelling and dancing around a pole every now and then."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
