# Site
name: "Startup Chiang Mai"
title: "Startup Chiang Mai"
description: "A repository for all things start up and digital in Chiang Mai"
meta_description: "A repository for all things start up and digital in Chiang Mai"
logo: 'assets/images/logo.png'
logo-small: 'assets/images/logo-small.png'
favicon: 'assets/images/logo.png'
baseurl: /startupchiangmai
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Lily:
    name: Lily
    display_name: Lily
    gravatar:
    email: lily@cnxweb.site
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. "

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
