# Site
name: "Startup Chiang Mai"
title: "Startup Chiang Mai"
description: "Startup Chiang Mai is a directory for all things startup and entrepreneurship. We also tell stories, share insights, and support community."
meta_description: "Startup Chiang Mai is a directory for all things startup and entrepreneurship. We also tell stories, share insights, and support community."
logo: 'assets/images/logo.png'
logo-small: '/assets/images/logo-small.png'
favicon: '/assets/images/favicon.ico'
baseurl:
google_analytics: 'UA-136959394-1'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
social:
  name: Startup Chiang Mai
  links:
    - startupchiangmai.com


# Authors
authors:
  lily:
    name: Lily
    display_name: Lily
    gravatar: 2fe6fb927f04d5b181c96f15b0a8e5b6
    email: lily@cnxweb.site
    web: lilybruns.com
    twitter: https://twitter.com/itslilybruns
    description: "Coder, copywriter, consultant, and cat lady. I'm a busybody who wants to know everything that's happening in Chiang Mai."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
